name: iqplayer
description: Simple awesome video player with subtitle (you can load from assets, file, network, string).
version: 0.4.1
homepage: https://github.com/MuhmdHsn313/IQPlayer

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ">=7.0.0 <8.0.0"
  equatable: ">=2.0.0 <2.1.0"
  video_player: ">=2.1.1 <2.2.0"
  http: ">=0.13.3 <0.14.0"
  simple_html_css: ">=3.0.1 <3.1.0"
  bloc: ">=7.0.0 <8.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ">=8.0.0"

flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
